"HTTP/1.0 200 \r\n"
"Content-Type: text/javascript\r\n"
"Cache-Control: max-age=1\r\n"
"\r\n"
"var letterCl = document.getElementById(\"letterColorId\");\r\n"
"var backgroundCl = document.getElementById(\"backColorId\");\r\n"
"var letterButton = document.getElementById(\"letterButton\");\r\n"
"var backgroundButton = document.getElementById(\"backgroundButton\");\r\n"
"var letterPopup = document.getElementById(\"letterPopUp\");\r\n"
"var backgroundPopup = document.getElementById(\"backgroundPopUp\");\r\n"
"\r\n"
"var letterColorPicker = new iro.ColorPicker(\"#letter-picker\", {\r\n"
"       layout: [\r\n"
"           { component: iro.ui.Slider, options: {sliderType: 'hue'} },\r\n"
"           { component: iro.ui.Slider, options: {sliderType: 'saturation'} },\r\n"
"         ]\r\n"
"       });\r\n"
"\r\n"
"letterColorPicker.on([\"color:init\"], function(color) {\r\n"
"  color.hexString = letterCl.value;\r\n"
"  letterCl.style.backgroundColor = letterCl.value;\r\n"
"});\r\n"
"\r\n"
"letterColorPicker.on([\"color:change\"], function(color) {\r\n"
"  letterCl.value = color.hexString;\r\n"
"  letterCl.style.backgroundColor = color.hexString;\r\n"
"});\r\n"
"\r\n"
"var backgroundColorPicker = new iro.ColorPicker(\"#background-picker\", {\r\n"
"         layout: [\r\n"
"           { component: iro.ui.Slider, options: {sliderType: 'hue'} },\r\n"
"           { component: iro.ui.Slider, options: {sliderType: 'value'} },\r\n"
"         ]\r\n"
"       });\r\n"
"\r\n"
"backgroundColorPicker.on([\"color:init\"], function(color) {\r\n"
"  color.hexString = backgroundCl.value;\r\n"
"  backgroundCl.style.backgroundColor = backgroundCl.value;\r\n"
"});\r\n"
"\r\n"
"backgroundColorPicker.on([\"color:change\"], function(color) {\r\n"
"  backgroundCl.value = color.hexString;\r\n"
"  backgroundCl.style.backgroundColor = color.hexString;\r\n"
"});\r\n"
"\r\n"
"backgroundButton.onclick = function() {\r\n"
"  if (backgroundPopup.style.display == \"block\") {\r\n"
"    backgroundPopup.style.display = \"none\";\r\n"
"  } else {\r\n"
"    backgroundPopup.style.display = \"block\";  \r\n"
"  }\r\n"
"}\r\n"
"\r\n"
"letterButton.onclick = function() {\r\n"
"  if (letterPopup.style.display == \"block\") {\r\n"
"    letterPopup.style.display = \"none\";\r\n"
"  } else {\r\n"
"    letterPopup.style.display = \"block\";  \r\n"
"  }\r\n"
"}\r\n"
"\r\n"
"// when the user clicks anywhere outside of the modal, close it\r\n"
"window.onclick = function(event) {\r\n"
"  if (event.target == letterPopup) {\r\n"
"    letterPopup.style.display = \"none\";\r\n"
"  }\r\n"
"  if (event.target == backgroundPopup) {\r\n"
"    backgroundPopup.style.display = \"none\";\r\n"
"  }\r\n"
"}\r\n"
